#!/bin/bash

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

echo
echo -e "${CYAN}CLEANING OLD BUILDS!${NC}"
echo
cd android && ./gradlew clean

echo
echo -e "${CYAN}BUILDING RELEASE!${NC}"
echo
./gradlew assembleRelease

echo
echo -e "${CYAN}DEPLOYING TO DEVICE!${NC}"
echo
cd ../ && react-native run-android --variant=release

echo
echo -e "${GREEN}SUCCESS!${NC}"
echo
echo -e "${CYAN}New Version running on Device...${NC}"
echo
